### ISSUE TITLE
Friend Status Tracker

### ISSUE THREAD

**Issue by jdmagic21** [jdmagic21/pokemonGoPokedex#14]
- [x] Create new model
- [x] Create API endpoints
- [x] Create views
    - [x] Index: list next friend level by estimated future date.
    - [x] Add
    - [x] Delete: model confirmation
    - [x] Update
- [x] Add main navigation
